### ISSUE TITLE
Typo Example 8.3 - in the simplification

### ISSUE THREAD

**Issue by kandolfp** [austindowney/Vibration-Mechanics#3]
Thanks for the excellent book, while going through the notes of Example 8.3 I think I stumbled over a typo:

https://github.com/austindowney/Vibration-Mechanics/blob/c5886d4d9b0d37e679a58b729908554e4ea5f460/source_material/Chapter_8_structural_dynamics/Chapter_8_structural_dynamics.tex#L409

By expanding (8.44) I get 

2 m^2 \omega^4  - 5 m k \omega^2 + 2 k^2 = 0

This also yields the correct solution given in (8.46 & 8.47)

**Comment by austindowney** [comment]
Thank you! 

I agree, this was an error in the math. I just updated the text so I'll go ahead and close this one. 

Thanks for letting me know.
